---
refresh_interval: 3 # seconds
urls:
  - https://www.coolblue.nl/product/852042/apple-airpods-pro-met-draadloze-oplaadcase.html
  - https://www.coolblue.nl/product/865867/playstation-5-digital-edition.html
  - https://www.coolblue.nl/product/865866/playstation-5.html
  - https://www.mediamarkt.nl/nl/product/_apple-airpods-pro-met-oplaadcase-1644480.html
  - https://www.mediamarkt.nl/nl/product/_sony-playstation-5-digital-edition-1665134.html
  - https://www.mediamarkt.nl/nl/product/_sony-playstation-5-disk-edition-1664768.html
  - https://www.bol.com/nl/p/apple-airpods-pro-met-active-noise-cancelling/9200000123229147
  - https://www.bol.com/nl/p/sony-playstation-5-console/9300000004162282
  - https://www.amazon.nl/Apple-MWP22ZM-A-AirPods-Pro/dp/B07ZPML7NP
  - https://www.amazon.nl/Sony-PlayStation-PlayStation%C2%AE5-Digital-Edition/dp/B08H98GVK8
  - https://www.amazon.nl/Sony-PlayStation-PlayStation%C2%AE5-Console/dp/B08H93ZRK9
  - https://www.nedgame.nl/playstation-5/sony-dualsense-wireless-controller/6022334263/
  - https://www.nedgame.nl/playstation-5/playstation-5-digital-edition--levering-begin-2021-/9647865079
  - https://www.nedgame.nl/playstation-5/playstation-5--levering-begin-2021-/6036644854
  - https://www.gamemania.nl/Accessories/controllers/145722_playstation-5-dualsense-draadloze-controller
  - https://www.gamemania.nl/Consoles/playstation-5/145721_playstation-5-digital-edition
  - https://www.gamemania.nl/Consoles/playstation-5/144093_playstation-5-disc-edition
  - https://www.intertoys.nl/shop/nl/intertoys/ps5-dualsense-controller
  - https://www.intertoys.nl/shop/nl/intertoys/games-elektronica/spelcomputers/ps5-digital-edition-825gb
  - https://www.intertoys.nl/shop/nl/intertoys/games-elektronica/spelcomputers/ps5-825gb
...
